name: build
on:
  workflow_dispatch:
  push:
    paths:
      - angie/**
permissions:
  contents: write
jobs:
    build: 
        runs-on: ubuntu-latest
        #runs-on: [self-hosted, linux]
        strategy:
            matrix:
                build_env:
                - httpconnect: "0.0.6"
                  quictls: "3.1.5"
                  angie: "1.5.1"

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Angie ${{ matrix.build_env.angie }}
              uses: docker/build-push-action@v5
              with:
                context: ./angie
                file: ./angie/angie.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/angie:latest, ${{ secrets.DOCKERHUB_USERNAME }}/angie:${{ matrix.build_env.angie }}
                build-args: |
                            ANGIE_VERSION=${{ matrix.build_env.angie }}

            - name: Build and push Angie ${{ matrix.build_env.angie }} with proxy_connect ${{ matrix.build_env.httpconnect }}  
              uses: docker/build-push-action@v5
              with:
                context: ./angie
                file: ./angie/angieproxy.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/angie:proxy, ${{ secrets.DOCKERHUB_USERNAME }}/angie:proxy-${{ matrix.build_env.angie }}
                build-args: |
                            ANGIE_VERSION=${{ matrix.build_env.angie }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}    

            - name: Build and push Angie ${{ matrix.build_env.angie }} with proxy_connect ${{ matrix.build_env.httpconnect }} and quicktls ${{ matrix.build_env.quictls }}
              uses: docker/build-push-action@v5
              with:
                context: ./angie
                file: ./angie/angieproxyquicktls.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/angie:proxy3, ${{ secrets.DOCKERHUB_USERNAME }}/angie:proxy3-${{ matrix.build_env.angie }}
                build-args: |
                            ANGIE_VERSION=${{ matrix.build_env.angie }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}   
                            QUICTLS_VERSION=${{ matrix.build_env.quictls }}

            - name: Build and push Angie DEB ${{ matrix.build_env.angie }} with proxy_connect ${{ matrix.build_env.httpconnect }}
              uses: docker/build-push-action@v5
              with:
                context: ./angie
                file: ./angie/angiedeb2.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/angie:deb, ${{ secrets.DOCKERHUB_USERNAME }}/angie:deb-${{ matrix.build_env.angie }}
                build-args: |
                            ANGIE_VERSION=${{ matrix.build_env.angie }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}                   
 