name: build (not ready)
on:
  workflow_dispatch:

jobs:
    build: 
        runs-on: ubuntu-latest
        strategy:
            matrix:
                build_env:
                - nginx: "1.25.4"
                  httpconnect: "0.0.6"

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
    
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.build
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-mod:build
                build-args: |
                            NGINX=${{ matrix.build_env.nginx }}
                            HTTPCONNECT=${{ matrix.build_env.httpconnect }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.builddeb
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-mod:deb
                build-args: |
                            NGINX=${{ matrix.build_env.nginx }}
                            HTTPCONNECT=${{ matrix.build_env.httpconnect }}

            - name: copy
              docker   
    














