name: build
on:
  workflow_dispatch:
jobs:
    build: 
        # runs-on: ubuntu-latest
        runs-on: [self-hosted, linux]
        strategy:
            matrix:
                build_env:
                - nginx: "1.25.5"
                  httpconnect: "0.0.6"
                  curl: "8.7.1"
                  quiche: "0.20.1"
                  boring: "0568c2c"
                  quic: "3.1.5"
        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Nginx alpineopenssl
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./nginx/Dockerfile.alpineopenssl
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:openssl, ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest, ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ matrix.build_env.nginx }}, 
                build-args: |
                            NGINX_VERSION=${{ matrix.build_env.nginx }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}

            - name: Build and push Nginx alpineboringssl
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./nginx/Dockerfile.alpineboringssl
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:boringssl
                build-args: |
                            NGINX_VERSION=${{ matrix.build_env.nginx }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}
                            BORINGSSL_COMMIT=${{ matrix.build_env.boring }}

            - name: Build and push Nginx alpinequictls
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./nginx/Dockerfile.alpinequictls
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:quicssl
                build-args: |
                            NGINX_VERSION=${{ matrix.build_env.nginx }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}
                            QUICTLS_VERSION=${{ matrix.build_env.quic }}

            - name: Build and push Nginx Deb
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./nginx/Dockerfile.builddeb
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:deb
                build-args: |
                            NGINX_VERSION=${{ matrix.build_env.nginx }}
                            NGINX_HTTP_PROXY_CONNECT_MODULE=${{ matrix.build_env.httpconnect }}
















