name: build Curl
on:
  workflow_dispatch:
  push:
    paths:
      - curl/**
      - .github/workflows/curl.yml
permissions:
  contents: write
jobs:
    build: 
        runs-on: ubuntu-latest
        #runs-on: [self-hosted, linux]
        strategy:
            matrix:
                build_env:
                - curl: "8.11.1"
                  quiche: "0.22.0"

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Curl ${{ matrix.build_env.curl }} quiche ${{ matrix.build_env.quiche }} 
              uses: docker/build-push-action@v6
              with:
                context: ./curl
                file: ./curl/alpine.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/curl:latest, ${{ secrets.DOCKERHUB_USERNAME }}/curl:${{ matrix.build_env.curl }}
                build-args: |
                            QUICHE_VERSION=${{ matrix.build_env.quiche }}
                            CURL_VERSION=${{ matrix.build_env.curl }}

            - name: Build and push Curl Deb ${{ matrix.build_env.curl }} quiche ${{ matrix.build_env.quiche }} 
              uses: docker/build-push-action@v6
              with:
                context: ./curl
                file: ./curl/deb.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/curl:deb, ${{ secrets.DOCKERHUB_USERNAME }}/curl:deb-${{ matrix.build_env.curl }}
                build-args: |
                            QUICHE_VERSION=${{ matrix.build_env.quiche }}
                            CURL_VERSION=${{ matrix.build_env.curl }}

            - name: Create a container from the image curl ${{ matrix.build_env.curl }} deb
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              continue-on-error: true
              run: |
                docker create --name curl-${{ matrix.build_env.curl }} ${{ secrets.DOCKERHUB_USERNAME }}/curl:deb-${{ matrix.build_env.curl }}
                docker cp curl-${{ matrix.build_env.curl }}:/tmp/curl_${{ matrix.build_env.curl }}_amd64.deb ./curl_${{ matrix.build_env.curl }}_amd64.deb
                ls -la
                sudo apt-get install -y gh

            - name: Push Curl ${{ matrix.build_env.curl }} deb to release
              env:
                GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }} # ${{ secrets.GITHUB_TOKEN }}
                token: ${{ secrets.WORKFLOW_TOKEN }}
              continue-on-error: true
              run: |
                  git config --global user.name '${{github.actor}}'
                  git config --global user.email '${{github.actor}}@users.noreply.github.com'
                  git tag -a "Curl${{ matrix.build_env.curl }}" -m "Curl${{ matrix.build_env.curl }}"
                  git push origin "Curl${{ matrix.build_env.curl }}"
                  gh release create "Curl${{ matrix.build_env.curl }}" ./curl_${{ matrix.build_env.curl }}_amd64.deb -t "Curl${{ matrix.build_env.curl }}" -n "Release notes"
