name: build Curl
on:
  workflow_dispatch:
  push:
    paths:
      - curl/**
permissions:
  contents: write
jobs:
    build: 
        runs-on: ubuntu-latest
        #runs-on: [self-hosted, linux]
        strategy:
            matrix:
                build_env:
                - curl: "8.8.0"
                  quiche: "0.21.0"

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Curl ${{ matrix.build_env.curl }} quiche ${{ matrix.build_env.quiche }} 
              uses: docker/build-push-action@v5
              with:
                context: ./curl
                file: ./curl/alpine.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/curl:latest, ${{ secrets.DOCKERHUB_USERNAME }}/curl:${{ matrix.build_env.curl }}
                build-args: |
                            QUICHE_VERSION=${{ matrix.build_env.quiche }}
                            CURL_VERSION=${{ matrix.build_env.curl }}

            - name: Build and push Curl Deb ${{ matrix.build_env.curl }} quiche ${{ matrix.build_env.quiche }} 
              uses: docker/build-push-action@v5
              with:
                context: ./curl
                file: ./curl/deb.dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/curl:deb, ${{ secrets.DOCKERHUB_USERNAME }}/curl:deb-${{ matrix.build_env.curl }}
                build-args: |
                            QUICHE_VERSION=${{ matrix.build_env.quiche }}
                            CURL_VERSION=${{ matrix.build_env.curl }}

