name: build Haproxy
on:
  workflow_dispatch:
  push:
    paths:
      - haproxy/**
      - .github/workflows/haproxy.yml
permissions:
  contents: write
jobs:
    build: 
        runs-on: ubuntu-latest
        #runs-on: [self-hosted, linux]
        strategy:
            matrix:
                build_env:
                - quictls: "3.1.5"
                  haproxy: "3.0.2"

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Build and push HAproxy ${{ matrix.build_env.haproxy }} quicktls ${{ matrix.build_env.nginx }}
              uses: docker/build-push-action@v5
              with:
                context: ./haproxy
                file: ./haproxy/Dockerfile.alpine
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/haproxy:latest, ${{ secrets.DOCKERHUB_USERNAME }}/haproxy:${{ matrix.build_env.haproxy }}
                build-args: |
                            HAPROXY_VERSION=${{ matrix.build_env.haproxy }}
                            QUICTLS_VERSION=${{ matrix.build_env.quictls }}
